import type { ApplicationReadiness, ExecutionTask, TaskState } from "./types";

const day = (offset: number, hour = 17) => { const date = new Date(); date.setHours(hour, 0, 0, 0); date.setDate(date.getDate() + offset); return date.toISOString(); };
const created = day(-12, 10);

function task(id: string, title: string, state: TaskState, offset: number | null, level: ExecutionTask["impact_level"], score: number, extra: Partial<ExecutionTask> = {}): ExecutionTask {
  return { id, title, description: "Complete the required action and keep the supporting evidence linked to every affected route.", state, priority: level === "critical" ? 1 : level === "high" ? 2 : 3, due_at: offset === null ? null : day(offset), due_timezone: "Asia/Karachi", due_source: "Official requirement deadline", estimated_minutes: 30, system_generated: true, impact_type: "application_readiness", impact_level: level, impact_score: score, source_type: "requirement", dedupe_key: `demo:${id}`, application_id: "app-leeds", application_title: "MSc Data Science · Leeds", assigned_name: "You", assigned_email: null, evidence_required: ["Clear scan or official record"], completion_note: null, completed_at: state === "completed" ? day(-2) : null, position: 1000, dependencies: [], impacts: [{ application_id: "app-leeds", entity_type: "application", entity_id: "app-leeds", application_title: "MSc Data Science · Leeds", impact_label: "Improves application readiness", readiness_delta: 12 }], activity: [{ id: `${id}-event`, event_type: "created", to_state: "todo", created_at: created }], created_at: created, updated_at: day(-1), ...extra };
}

export function demoExecutionData(): { tasks: ExecutionTask[]; readiness: ApplicationReadiness[] } {
  const tasks = [
    task("task-english", "Book an accepted English language test", "in_progress", 2, "critical", 100, { description: "Choose an accepted IELTS/PTE date early enough for results to arrive before the application deadline.", impact_type: "eligibility", estimated_minutes: 20, evidence_required: ["Test booking confirmation", "Result when issued"], impacts: [{ application_id: "app-leeds", entity_type: "application", entity_id: "app-leeds", application_title: "MSc Data Science · Leeds", impact_label: "Removes English eligibility blocker", readiness_delta: 18 }, { application_id: "app-chevening", entity_type: "scholarship", entity_id: "app-chevening", application_title: "Chevening Scholarship", impact_label: "Strengthens evidence plan", readiness_delta: 7 }] }),
    task("task-transcript", "Upload final bachelor transcript", "todo", 0, "critical", 98, { impact_type: "document", estimated_minutes: 10, evidence_required: ["All pages", "Award date", "Institution stamp"], impacts: [{ application_id: "app-leeds", entity_type: "application", entity_id: "app-leeds", application_title: "MSc Data Science · Leeds", impact_label: "Unblocks academic evidence", readiness_delta: 18 }, { application_id: "app-saarland", entity_type: "application", entity_id: "app-saarland", application_title: "MSc Data Science · Saarland", impact_label: "Completes degree evidence", readiness_delta: 14 }] }),
    task("task-referee", "Confirm academic referee availability", "waiting", 4, "high", 82, { assigned_name: "Dr. Ahmed", assigned_email: "referee@example.edu", source_type: "system", description: "The invitation was sent. Follow up if no response arrives within three days.", impact_type: "application_readiness", evidence_required: ["Referee acceptance"], impacts: [{ application_id: "app-chevening", entity_type: "scholarship", entity_id: "app-chevening", application_title: "Chevening Scholarship", impact_label: "Secures required reference", readiness_delta: 15 }] }),
    task("task-math", "Verify mathematics module coverage", "blocked", 7, "high", 78, { description: "Map transcript modules to the published mathematics prerequisite. This waits for the transcript upload.", dependencies: [{ depends_on_task_id: "task-transcript", relation: "blocks", title: "Upload final bachelor transcript", state: "todo" }], evidence_required: ["Transcript", "Module descriptions"], impacts: [{ application_id: "app-leeds", entity_type: "application", entity_id: "app-leeds", application_title: "MSc Data Science · Leeds", impact_label: "Confirms prerequisite eligibility", readiness_delta: 16 }] }),
    task("task-statement", "Finish personal statement evidence outline", "ready_for_review", 1, "high", 76, { impact_type: "application_readiness", estimated_minutes: 75, source_type: "personal", system_generated: false, evidence_required: ["Three verified evidence stories", "Programme-specific motivation"], impacts: [{ application_id: "app-leeds", entity_type: "application", entity_id: "app-leeds", application_title: "MSc Data Science · Leeds", impact_label: "Completes writing component", readiness_delta: 11 }] }),
    task("task-funding", "Document first-year funding gap", "todo", 12, "medium", 55, { impact_type: "funding", due_source: "Student planning target", evidence_required: ["Confirmed contribution", "Current bank evidence"], impacts: [{ application_id: "app-leeds", entity_type: "funding", entity_id: "app-leeds", application_title: "MSc Data Science · Leeds", impact_label: "Makes affordability risk visible", readiness_delta: 5 }] }),
    task("task-passport", "Renew passport", "todo", -3, "critical", 100, { impact_type: "visa", due_source: "Student planning target", estimated_minutes: 45, source_type: "profile_gap", evidence_required: ["Renewal receipt", "New passport biodata page"], impacts: [{ application_id: null, entity_type: "profile", entity_id: null, application_title: "All international routes", impact_label: "Prevents identity and visa delays", readiness_delta: 20 }] }),
    task("task-shortlist", "Review scholarship shortlist", "completed", -2, "medium", 50, { impact_type: "scholarship", evidence_required: [], completion_note: "Saved three realistic awards to portfolio.", impacts: [{ application_id: "app-chevening", entity_type: "scholarship", entity_id: "app-chevening", application_title: "Scholarship portfolio", impact_label: "Focuses application effort", readiness_delta: 6 }] }),
  ];
  return { tasks, readiness: [
    { application_id: "app-leeds", application_title: "MSc Data Science · Leeds", score: 62, confirmed_count: 5, total_count: 9, blocking_count: 2, missing_count: 4, overdue_critical_count: 1, next_task_id: "task-transcript", updated_at: new Date().toISOString() },
    { application_id: "app-saarland", application_title: "MSc Data Science · Saarland", score: 74, confirmed_count: 6, total_count: 8, blocking_count: 1, missing_count: 2, overdue_critical_count: 0, next_task_id: "task-transcript", updated_at: new Date().toISOString() },
    { application_id: "app-chevening", application_title: "Chevening Scholarship", score: 48, confirmed_count: 4, total_count: 9, blocking_count: 1, missing_count: 5, overdue_critical_count: 0, next_task_id: "task-referee", updated_at: new Date().toISOString() },
  ] };
}
