import type { CountryIntelligence, InstitutionDirectoryItem } from "./types";

const verifiedAt = "2026-08-04T00:00:00Z";
const immigrationReview = "2026-09-04T00:00:00Z";

export const fallbackCountries: CountryIntelligence[] = [
  {
    code: "GB", slug: "united-kingdom", name: "United Kingdom", flag: "🇬🇧", currencyCode: "GBP", currencySymbol: "£", primaryLanguage: "English", studentRoute: "Student visa", visaDifficulty: "moderate", visaFeeAmount: 558, visaFeeCurrency: "GBP", proofFundsAmount: 10539, proofFundsCurrency: "GBP", proofFundsMonths: 9, workHours: 20, postStudyMonths: 18, monthlyCostLow: 1171, monthlyCostHigh: 2200, costCurrency: "GBP", lastVerifiedAt: verifiedAt, nextReviewAt: immigrationReview,
    summary: "Large programme market with clear sponsor and visa rules; cost varies sharply by city.", healthcare: "Student applicants normally pay the Immigration Health Surcharge and receive NHS access under its terms.", work: "Degree-level students at eligible sponsors are normally limited to 20 hours per week during term.", postStudy: "The Graduate route is scheduled at 18 months for non-doctoral applications made from 1 January 2027; verify before planning.", climate: "Temperate and often wet, with mild summers and cool winters.", community: "Major university cities have established Muslim and South Asian communities; verify facilities by postcode.", visaUncertainty: "CAS timing, financial evidence, rule changes and possible ATAS requirements can alter readiness.",
    cities: [
      { id: "gb-leeds", name: "Leeds", monthlyCostLow: 862, monthlyCostHigh: 1833, accommodationLow: 507, accommodationHigh: 1300, deposit: "Check the exact refundable deposit and advance-rent term before payment.", transport: "Walkable student areas with bus and rail links.", safety: "Use institution safety services and compare campus-to-home routes.", climate: "Cool, wet winters and mild summers.", community: "Established Muslim and South Asian communities with multiple halal and worship options.", confidence: 85 },
      { id: "gb-london", name: "London", monthlyCostLow: 1529, monthlyCostHigh: 2600, accommodationLow: 900, accommodationHigh: 1800, deposit: "Deposits and advance rent can materially increase arrival cash.", transport: "Extensive public transport with a significant recurring cost.", safety: "Compare neighbourhood, late travel and campus commute rather than using one city-wide score.", climate: "Mild and wet; urban summers can be warmer.", community: "Very large and diverse Muslim and South Asian communities.", confidence: 60 },
      { id: "gb-manchester", name: "Manchester", monthlyCostLow: 1050, monthlyCostHigh: 1900, accommodationLow: 550, accommodationHigh: 1200, deposit: "Confirm utilities and contract terms.", transport: "Strong tram, bus and rail network.", safety: "Use university neighbourhood guidance.", climate: "Cool, wet and often cloudy.", community: "Large Muslim and South Asian communities.", confidence: 55 },
    ], facts: [],
  },
  {
    code: "DE", slug: "germany", name: "Germany", flag: "🇩🇪", currencyCode: "EUR", currencySymbol: "€", primaryLanguage: "German", studentRoute: "Study visa / residence permit", visaDifficulty: "moderate", visaFeeAmount: 75, visaFeeCurrency: "EUR", proofFundsAmount: 11904, proofFundsCurrency: "EUR", proofFundsMonths: 12, workHours: 20, postStudyMonths: 18, monthlyCostLow: 900, monthlyCostHigh: 1200, costCurrency: "EUR", lastVerifiedAt: verifiedAt, nextReviewAt: immigrationReview,
    summary: "Strong public-university value with more programme and city variation than tuition headlines imply.", healthcare: "Compliant health insurance is mandatory for enrolment and residence purposes.", work: "Students may generally work 140 full or 280 half days yearly, or up to 20 hours weekly under current rules.", postStudy: "Graduates can generally seek qualified work for up to 18 months.", climate: "Four seasons with colder winters and regional variation.", community: "Major cities offer established Muslim and South Asian communities; smaller towns require a location check.", visaUncertainty: "Blocked-account levels, recognition, language and programme equivalence require current verification.",
    cities: [
      { id: "de-munich", name: "Munich", monthlyCostLow: 1200, monthlyCostHigh: 1700, accommodationLow: 300, accommodationHigh: 1000, deposit: "Student housing can require about €500; private-market terms vary.", transport: "Dense public transport with student and national-ticket options.", safety: "Use local and institution guidance for neighbourhood decisions.", climate: "Cold winters and warm summers.", community: "Established international and Muslim communities.", confidence: 82 },
      { id: "de-saarbrucken", name: "Saarbrücken", monthlyCostLow: 900, monthlyCostHigh: 1150, accommodationLow: 300, accommodationHigh: 600, deposit: "Confirm deposit and utilities with the provider.", transport: "Compact city with buses and regional rail.", safety: "Use current university guidance.", climate: "Cool winters and mild summers.", community: "Smaller community; check facility distance from campus.", confidence: 60 },
    ], facts: [],
  },
  {
    code: "NL", slug: "netherlands", name: "Netherlands", flag: "🇳🇱", currencyCode: "EUR", currencySymbol: "€", primaryLanguage: "Dutch", studentRoute: "Residence permit for study", visaDifficulty: "moderate", visaFeeAmount: 254, visaFeeCurrency: "EUR", proofFundsAmount: 13569.24, proofFundsCurrency: "EUR", proofFundsMonths: 12, workHours: 16, postStudyMonths: 12, monthlyCostLow: 1000, monthlyCostHigh: 1500, costCurrency: "EUR", lastVerifiedAt: verifiedAt, nextReviewAt: immigrationReview,
    summary: "Strong English-taught options, but housing scarcity materially affects feasibility.", healthcare: "Study-only students generally need adequate private/home-country cover; paid work can change insurance duties.", work: "Non-EU students can normally work up to 16 hours weekly or only in summer, subject to employer conditions.", postStudy: "Eligible graduates may apply for a one-year orientation permit.", climate: "Mild, windy and frequently wet maritime climate.", community: "Major Dutch cities have visible Muslim and South Asian communities.", visaUncertainty: "Recognised-sponsor status, annual study norm and housing availability are major dependencies.",
    cities: [
      { id: "nl-delft", name: "Delft", monthlyCostLow: 1050, monthlyCostHigh: 1550, accommodationLow: 450, accommodationHigh: 1000, deposit: "Use institution-approved channels and verify advance payments.", transport: "Cycling, buses and national rail.", safety: "Cycle safety and housing scams are material practical risks.", climate: "Mild, windy and wet.", community: "International community with access to Rotterdam and The Hague.", confidence: 68 },
      { id: "nl-amsterdam", name: "Amsterdam", monthlyCostLow: 1300, monthlyCostHigh: 1900, accommodationLow: 650, accommodationHigh: 1250, deposit: "High demand increases scam and advance-payment risk.", transport: "Extensive cycling and public transport.", safety: "Prioritise verified housing and cycle safety.", climate: "Mild and frequently wet.", community: "Large diverse Muslim and South Asian communities.", confidence: 65 },
    ], facts: [],
  },
  {
    code: "IE", slug: "ireland", name: "Ireland", flag: "🇮🇪", currencyCode: "EUR", currencySymbol: "€", primaryLanguage: "English", studentRoute: "Long Stay D / Stamp 2", visaDifficulty: "moderate", visaFeeAmount: 60, visaFeeCurrency: "EUR", proofFundsAmount: 10000, proofFundsCurrency: "EUR", proofFundsMonths: 12, workHours: 20, postStudyMonths: 24, monthlyCostLow: 1200, monthlyCostHigh: 2250, costCurrency: "EUR", lastVerifiedAt: verifiedAt, nextReviewAt: immigrationReview,
    summary: "English-speaking study route with a smaller institution market and severe Dublin accommodation pressure.", healthcare: "Private medical insurance is compulsory for non-EU/EEA students.", work: "Stamp 2 students may normally work 20 hours in term and 40 during specified vacations.", postStudy: "Level 9+ graduates may receive up to 24 months; Level 8 is normally 12 months.", climate: "Mild, windy and rainy maritime climate.", community: "Dublin and other university cities have active Muslim and South Asian communities.", visaUncertainty: "Finance, eligible-programme status, registration and accommodation must all be checked.",
    cities: [
      { id: "ie-dublin", name: "Dublin", monthlyCostLow: 1754, monthlyCostHigh: 2254, accommodationLow: 750, accommodationHigh: 1333, deposit: "One month’s rent is commonly required as a refundable deposit.", transport: "Bus, rail and tram; housing location drives commute cost.", safety: "Accommodation scams and late travel planning are material concerns.", climate: "Mild, windy and rainy.", community: "Large international, Muslim and South Asian communities.", confidence: 88 },
      { id: "ie-cork", name: "Cork", monthlyCostLow: 1200, monthlyCostHigh: 1800, accommodationLow: 650, accommodationHigh: 1100, deposit: "A one-month refundable deposit is common.", transport: "Bus-based transport with a compact centre.", safety: "Use institution accommodation services.", climate: "Mild and rainy.", community: "Active international community with local Muslim facilities.", confidence: 58 },
    ], facts: [],
  },
];

const institution = (partial: Partial<InstitutionDirectoryItem> & Pick<InstitutionDirectoryItem, "id" | "slug" | "name" | "shortName" | "countryCode" | "countryName" | "flag" | "city" | "websiteUrl" | "summary">): InstitutionDirectoryItem => ({ type: "university", admissionsUrl: null, publicPrivate: "public", degreeAwarding: true, sponsorStatus: "Official sponsor/eligibility status must be rechecked before application", lastVerifiedAt: verifiedAt, nextReviewAt: "2026-11-04T00:00:00Z", campusCount: partial.city ? 1 : 0, programmeCount: 0, rankings: [], equivalencies: [], requirements: [], ...partial });

export const fallbackInstitutions: InstitutionDirectoryItem[] = [
  institution({ id: "leeds", slug: "university-of-leeds", name: "University of Leeds", shortName: "Leeds", countryCode: "GB", countryName: "United Kingdom", flag: "🇬🇧", city: "Leeds", websiteUrl: "https://www.leeds.ac.uk", summary: "Research-intensive university with broad taught postgraduate provision.", rankings: [{ id: "leeds-qs-2026", publisher: "QS", name: "World University Rankings", year: 2026, rankLabel: "86" }], equivalencies: [
    { id: "leeds-pk", originCountry: "Pakistan", studyLevel: "postgraduate", qualification: "Four-year bachelor or two-year master after shorter bachelor", minimumResult: "2:1 mapping: typically 70% or GPA 2.8–3.0", state: "published_threshold", notes: "Programme requirements may be higher." },
    { id: "leeds-in", originCountry: "India", studyLevel: "postgraduate", qualification: "Three- or four-year bachelor", minimumResult: "2:1 mapping: typically 60% / first class", state: "published_threshold", notes: "Institution and programme conditions apply." },
    { id: "leeds-bd", originCountry: "Bangladesh", studyLevel: "postgraduate", qualification: "Four-year bachelor or one- to two-year master", minimumResult: "2:1 mapping: typically 70%, master GPA 3.0 or bachelor GPA 3.2", state: "published_threshold", notes: "Programme requirements may be higher." },
  ] }),
  institution({ id: "manchester", slug: "university-of-manchester", name: "University of Manchester", shortName: "Manchester", countryCode: "GB", countryName: "United Kingdom", flag: "🇬🇧", city: "Manchester", websiteUrl: "https://www.manchester.ac.uk", summary: "Large research university with broad STEM, business and humanities provision." }),
  institution({ id: "sheffield", slug: "university-of-sheffield", name: "University of Sheffield", shortName: "Sheffield", countryCode: "GB", countryName: "United Kingdom", flag: "🇬🇧", city: "Sheffield", websiteUrl: "https://www.sheffield.ac.uk", summary: "Research university with engineering, computing and interdisciplinary options." }),
  institution({ id: "tum", slug: "technical-university-of-munich", name: "Technical University of Munich", shortName: "TUM", countryCode: "DE", countryName: "Germany", flag: "🇩🇪", city: "Munich", websiteUrl: "https://www.tum.de", summary: "Research university focused on engineering, computing, science and management.", rankings: [{ id: "tum-qs-2026", publisher: "QS", name: "World University Rankings", year: 2026, rankLabel: "=22" }] }),
  institution({ id: "saarland", slug: "saarland-university", name: "Saarland University", shortName: "Saarland", countryCode: "DE", countryName: "Germany", flag: "🇩🇪", city: "Saarbrücken", websiteUrl: "https://www.uni-saarland.de", summary: "Research university with a particularly strong computer-science ecosystem." }),
  institution({ id: "rwth", slug: "rwth-aachen", name: "RWTH Aachen University", shortName: "RWTH", countryCode: "DE", countryName: "Germany", flag: "🇩🇪", city: "Aachen", websiteUrl: "https://www.rwth-aachen.de", summary: "Large technical university with extensive engineering and science provision." }),
  institution({ id: "delft", slug: "tu-delft", name: "Delft University of Technology", shortName: "TU Delft", countryCode: "NL", countryName: "Netherlands", flag: "🇳🇱", city: "Delft", websiteUrl: "https://www.tudelft.nl", summary: "Technology-focused research university with competitive MSc admissions.", rankings: [{ id: "delft-qs-2026", publisher: "QS", name: "World University Rankings", year: 2026, rankLabel: "=47" }] }),
  institution({ id: "uva", slug: "university-of-amsterdam", name: "University of Amsterdam", shortName: "UvA", countryCode: "NL", countryName: "Netherlands", flag: "🇳🇱", city: "Amsterdam", websiteUrl: "https://www.uva.nl", summary: "Broad research university with many English-taught graduate programmes." }),
  institution({ id: "tue", slug: "eindhoven-university-of-technology", name: "Eindhoven University of Technology", shortName: "TU/e", countryCode: "NL", countryName: "Netherlands", flag: "🇳🇱", city: "Eindhoven", websiteUrl: "https://www.tue.nl", summary: "Technical university connected to a major engineering and technology region." }),
  institution({ id: "trinity", slug: "trinity-college-dublin", name: "Trinity College Dublin", shortName: "Trinity", countryCode: "IE", countryName: "Ireland", flag: "🇮🇪", city: "Dublin", websiteUrl: "https://www.tcd.ie", summary: "Research university in central Dublin with broad postgraduate provision.", rankings: [{ id: "trinity-qs-2026", publisher: "QS", name: "World University Rankings", year: 2026, rankLabel: "75" }], equivalencies: (["Pakistan", "India", "Bangladesh"] as const).map((originCountry) => ({ id: `trinity-${originCountry}`, originCountry, studyLevel: "postgraduate", qualification: "Recognised bachelor degree", minimumResult: "Equivalent of Irish 2.1 honours", state: "case_by_case" as const, notes: "Academic Registry and the programme make the final assessment." })) }),
  institution({ id: "ucd", slug: "university-college-dublin", name: "University College Dublin", shortName: "UCD", countryCode: "IE", countryName: "Ireland", flag: "🇮🇪", city: "Dublin", websiteUrl: "https://www.ucd.ie", summary: "Large research university with a broad international programme portfolio." }),
  institution({ id: "ucc", slug: "university-college-cork", name: "University College Cork", shortName: "UCC", countryCode: "IE", countryName: "Ireland", flag: "🇮🇪", city: "Cork", websiteUrl: "https://www.ucc.ie", summary: "Research university offering broad postgraduate study in Cork." }),
];

