"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AlertCircle, ArrowLeft, ArrowRight, Bell, BookOpenCheck, CalendarDays, Check, CheckCircle2, ChevronDown, Clock3, Database, Download, Eye, FileCheck2, FileText, GraduationCap, Heart, KeyRound, Lock, Mail, Pencil, Save, Settings, ShieldCheck, Sparkles, Target, Trash2, UserRound, WalletCards, X } from "lucide-react";
import type { Opportunity } from "@/modules/product/demo-data";
import { useWorkspace } from "@/lib/use-workspace";
import { CountryFlag } from "@/components/country/country-flag";
import type { ProductAccess } from "@/lib/product/entitlements";

type Toast = { title: string; text: string } | null;

export function StudentProfileCenter() {
  const [tab, setTab] = useState<"report" | "details" | "evidence">("report");
  const [editing, setEditing] = useState<string | null>(null); const [toast, setToast] = useState<Toast>(null);
  const sections = [
    { id: "identity", icon: UserRound, title: "Identity and origin", state: "Verified", summary: "Pakistani citizen · living in Pakistan", fields: [["Citizenship", "Pakistan"], ["Current country", "Pakistan"], ["Timezone", "Asia/Karachi"], ["Preferred currency", "PKR"]] },
    { id: "academic", icon: GraduationCap, title: "Academic record", state: "Needs evidence", summary: "BS Computer Science · 3.42/4.00", fields: [["Qualification", "BS Computer Science"], ["Institution", "University of the Punjab"], ["Grade", "3.42 / 4.00"], ["Graduation", "2025 · completed"]] },
    { id: "language", icon: BookOpenCheck, title: "English readiness", state: "Action needed", summary: "IELTS planned · no result attached", fields: [["Status", "Preparing"], ["Test", "IELTS Academic"], ["Target", "7.0 overall"], ["Evidence", "Not uploaded"]] },
    { id: "goals", icon: Target, title: "Study goals", state: "Complete", summary: "Data and AI master’s · September 2027", fields: [["Level", "Taught master’s"], ["Field", "Data Science and AI"], ["Intake", "September 2027"], ["Destinations", "UK, Germany, wider Europe"]] },
    { id: "funding", icon: WalletCards, title: "Funding reality", state: "Review", summary: "Major funding required · PKR 3.4m available", fields: [["Funding need", "Major funding"], ["Contribution", "PKR 3,400,000"], ["Sponsor", "Family contribution"], ["Proof", "Not confirmed"]] },
  ];
  const showToast = (title: string, text: string) => { setToast({ title, text }); window.setTimeout(() => setToast(null), 2600); };
  return <div className="complete-screen">
    <header className="complete-head"><div><span className="product-eyebrow">Profile intelligence</span><h1>Your evidence, translated into decisions.</h1><p>Review what the system understands, correct individual facts, and see exactly which routes change.</p></div><div><Link className="product-button product-button--secondary" href="/?retake=1"><Sparkles size={16} /> Update pathway</Link><button className="product-button product-button--primary" onClick={() => setEditing("identity")}><Pencil size={16} /> Edit profile</button></div></header>
    <nav className="complete-tabs">{[["report","Pathway report"],["details","Profile details"],["evidence","Evidence map"]].map(([id,label]) => <button className={tab === id ? "active" : ""} key={id} onClick={() => setTab(id as typeof tab)}>{label}</button>)}</nav>
    {tab === "report" && <ProfileReport onEdit={() => setEditing("academic")} />}
    {tab === "details" && <div className="profile-detail-layout"><aside className="profile-completeness"><div className="profile-completeness__ring"><strong>72%</strong><span>complete</span></div><h3>Three facts need evidence</h3><p>Improving these will make recommendations more specific; it will not create an admission probability.</p><div><span><i className="critical" /> English test</span><span><i className="high" /> Mathematics modules</span><span><i className="medium" /> Funding proof</span></div></aside><section className="profile-detail-sections">{sections.map(({ id, icon: Icon, title, state, summary, fields }) => <article key={id}><header><span><Icon /></span><div><h2>{title}</h2><p>{summary}</p></div><Status text={state} /><button onClick={() => setEditing(id)}><Pencil /> Edit</button></header><div>{fields.map(([label,value]) => <span key={label}><small>{label}</small><strong>{value}</strong></span>)}</div></article>)}</section></div>}
    {tab === "evidence" && <EvidenceMap onUpload={() => showToast("Upload prepared", "The secure file chooser will connect directly to your Supabase storage bucket.")} />}
    {editing && <ProfileEditDialog section={sections.find((item) => item.id === editing) ?? sections[0]} onClose={() => setEditing(null)} onSave={() => { setEditing(null); showToast("Profile updated", "Affected recommendations and applications have been marked for recalculation."); }} />}
    {toast && <ToastMessage {...toast} />}
  </div>;
}

function ProfileReport({ onEdit }: { onEdit: () => void }) {
  const lanes = [{ name: "United Kingdom", state: "Strong research lane", tone: "green", progress: 78, checks: "2 conditions" }, { name: "Germany", state: "Promising lower-cost lane", tone: "blue", progress: 70, checks: "3 checks" }, { name: "Erasmus Mundus", state: "Funding-first lane", tone: "violet", progress: 59, checks: "4 conditions" }];
  return <div className="pathway-report"><section className="report-hero"><div><span className="product-eyebrow">Your current conclusion</span><h2>Build a balanced UK and Germany shortlist while treating full funding as a separate dependency.</h2><p>Your computing background supports Data and AI research. Mathematics evidence, English readiness and verified funding rules still control which routes can move forward.</p><div><button className="product-button product-button--primary" onClick={onEdit}>Resolve highest-impact gap <ArrowRight /></button><Link className="product-button product-button--secondary" href="/discover">Explore recommendations</Link></div></div><aside><strong>Medium</strong><span>evidence confidence</span><p>14 verified facts · 3 unresolved</p><small><ShieldCheck /> No acceptance probability</small></aside></section>
    <section className="report-grid"><article className="report-lanes"><header><div><span className="product-eyebrow">Research lanes</span><h2>Where to concentrate first</h2></div><span>Based on current evidence</span></header>{lanes.map((lane,index) => <Link href="/discover" key={lane.name}><b>0{index+1}</b><span><strong>{lane.name}</strong><small>{lane.state}</small><i><em className={lane.tone} style={{width:`${lane.progress}%`}} /></i></span><Status text={lane.checks} /><ArrowRight /></Link>)}</article><article className="report-gaps"><header><span className="product-eyebrow">Decision blockers</span><h2>What changes the result</h2></header><div><span className="critical"><AlertCircle /></span><p><strong>English test evidence</strong><small>Blocks confirmed language eligibility across two routes.</small></p><b>Critical</b></div><div><span className="high"><FileCheck2 /></span><p><strong>Mathematics coverage</strong><small>Controls programme-level academic eligibility.</small></p><b>High</b></div><div><span className="medium"><WalletCards /></span><p><strong>Funding proof</strong><small>Changes feasibility, not academic fit.</small></p><b>Medium</b></div><Link href="/workspace">Open action plan <ArrowRight /></Link></article></section>
    <section className="report-method"><ShieldCheck /><div><strong>How this report was formed</strong><p>Validated profile facts → hard eligibility rules → evidence and funding checks → conditional research lanes → prioritized actions. Unknown evidence remains visible.</p></div><Link href="/help">View methodology</Link></section></div>;
}

function EvidenceMap({ onUpload }: { onUpload: () => void }) { const rows = [{ title: "Passport", category: "Identity", state: "Verified", affects: "3 applications" }, { title: "BS transcript", category: "Academic", state: "Needs review", affects: "3 applications" }, { title: "Degree certificate", category: "Academic", state: "Verified", affects: "2 applications" }, { title: "IELTS result", category: "Language", state: "Missing", affects: "2 applications" }, { title: "Funding statement", category: "Financial", state: "Missing", affects: "Leeds feasibility" }]; return <section className="evidence-map"><header><div><span className="product-eyebrow">Reusable evidence</span><h2>One record, every affected decision.</h2><p>Documents remain private. Each application stores its own acceptance state.</p></div><button className="product-button product-button--primary" onClick={onUpload}><FileCheck2 /> Add evidence</button></header><div className="evidence-map__table"><div><span>Evidence</span><span>Category</span><span>State</span><span>Used by</span><i /></div>{rows.map((row) => <button key={row.title} onClick={onUpload}><span><FileText /><strong>{row.title}</strong></span><span>{row.category}</span><Status text={row.state} /><span>{row.affects}</span><ArrowRight /></button>)}</div></section>; }

function ProfileEditDialog({ section, onClose, onSave }: { section: { title: string; fields: string[][] }; onClose: () => void; onSave: () => void }) { return <div className="complete-modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><form className="complete-modal" role="dialog" aria-modal="true" aria-labelledby="profile-edit-title" onSubmit={(e) => { e.preventDefault(); onSave(); }}><header><div><span className="product-eyebrow">Edit verified facts</span><h2 id="profile-edit-title">{section.title}</h2><p>Changes show their downstream impact before being applied.</p></div><button type="button" onClick={onClose}><X /></button></header><div className="complete-modal__body">{section.fields.map(([label,value],index) => <label key={label}>{label}{index === 0 || label.includes("Status") || label.includes("Need") ? <span className="complete-select"><select defaultValue={value}><option>{value}</option><option>Not provided</option><option>Needs review</option></select><ChevronDown /></span> : <input defaultValue={value} />}</label>)}<div className="impact-notice"><Sparkles /><span><strong>3 recommendations may change</strong><small>Leeds, Saarland and Chevening will be recalculated after saving.</small></span></div></div><footer><button type="button" onClick={onClose}>Cancel</button><button className="primary" type="submit"><Save /> Save and recalculate</button></footer></form></div>; }

export function OpportunityDetail({ id, opportunity }: { id: string; opportunity?: Opportunity }) {
  if (!opportunity) return <div className="complete-screen"><Link className="back-link" href="/discover"><ArrowLeft /> Back to discovery</Link><section className="detail-panel wide"><span className="product-eyebrow">Verified catalogue</span><h1>Opportunity not available</h1><p>This route is not present in the current live catalogue. No demonstration record was substituted.</p></section></div>;
  return <LiveOpportunityDetail id={id} opportunity={opportunity} />;
}

function LiveOpportunityDetail({ id, opportunity }: { id: string; opportunity: Opportunity }) {
  const workspace = useWorkspace();
  const item = opportunity; const [tab,setTab]=useState("Overview"); const [saved,setSaved]=useState(Boolean(item.saved)); const [starting,setStarting]=useState(false); const [toast,setToast]=useState<Toast>(null);
  useEffect(() => { setSaved(Boolean(item.saved)); }, [item.id, item.saved]);
  const notify=(title:string,text:string)=>{setToast({title,text});window.setTimeout(()=>setToast(null),2500)};
  const toggleSaved=async()=>{if(workspace.mode==="live"&&!workspace.authenticated){window.location.href=`/auth?next=${encodeURIComponent(`/discover/${id}`)}`;return;}const next=!saved;setSaved(next);try{if(workspace.mode==="live")await workspace.act({resource:"portfolio",action:next?"save":"remove",entityType:item.kind==="Programme"?"programme":"scholarship",entityId:item.id});notify(next?"Saved to portfolio":"Removed from portfolio","Your decision workspace is now up to date.");}catch(reason){setSaved(!next);notify("Could not update portfolio",reason instanceof Error?reason.message:"Please try again.");}};
  const startApplication=async()=>{if(workspace.mode==="live"&&!workspace.authenticated){window.location.href=`/auth?next=${encodeURIComponent(`/discover/${id}`)}`;return;}setStarting(true);try{if(workspace.mode==="live")await workspace.act({resource:"application",action:"create",title:item.title,providerName:item.provider,...(item.kind==="Programme"?{programmeId:item.id}:{scholarshipId:item.id})});notify("Application workspace created","Opening your requirements, tasks, evidence and deadline plan.");window.setTimeout(()=>{window.location.href="/applications";},700);}catch(reason){notify("Could not create application",reason instanceof Error?reason.message:"Please try again.");setStarting(false);}};
  const score=item.matchScore??0;
  return <div className="complete-screen opportunity-page"><Link className="back-link" href="/discover"><ArrowLeft /> Back to discovery</Link><section className="opportunity-hero"><div><div className="opportunity-hero__meta"><CountryFlag code={item.flag} name={item.country} /><span className="product-eyebrow">{item.kind} · {item.country}</span><Status text={item.freshness} /></div><h1>{item.title}</h1><p>{item.provider}</p><div className="opportunity-hero__facts"><span><WalletCards /> <b>{item.value.replaceAll("_"," ")}</b><small>Funding</small></span><span><CalendarDays /> <b>{item.deadline}</b><small>Application deadline</small></span><span><ShieldCheck /> <b>{score?`${score}%`:item.match}</b><small>{score?"Profile match":"Complete profile to score"}</small></span></div></div><aside><button className="product-button product-button--primary" disabled={starting} onClick={()=>void startApplication()}>{starting?"Creating…":"Start application"} <ArrowRight /></button><button className="product-button product-button--secondary" onClick={()=>void toggleSaved()}><Heart fill={saved?"currentColor":"none"} /> {saved?"Saved":"Save route"}</button><small><Database /> {item.freshness === "Verified" ? "All displayed details confirmed from the official source" : item.freshness === "Provisional" ? "Official source found; some details still need confirmation" : "Source review is due"}</small></aside></section>
    <nav className="complete-tabs">{["Overview","Eligibility","Funding","Timeline","Sources"].map((label)=><button className={tab===label?"active":""} key={label} onClick={()=>setTab(label)}>{label}</button>)}</nav>
    {tab==="Overview"&&<OpportunityOverview item={item}/>} {tab==="Eligibility"&&<EligibilityPanel item={item}/>} {tab==="Funding"&&<FundingPanel item={item}/>} {tab==="Timeline"&&<TimelinePanel item={item}/>} {tab==="Sources"&&<SourcesPanel item={item}/>} {toast&&<ToastMessage {...toast}/>}</div>;
}
function OpportunityOverview({item}:{item:Opportunity}){return <div className="opportunity-content"><main><section className="detail-panel detail-panel--signals"><span className="product-eyebrow">Why it fits you</span><h2>Your strongest signals</h2><div className="signal-grid">{item.reasons.slice(0,2).map((reason)=><div className="decision-row pass" key={reason}><CheckCircle2/><span><strong>Good signal</strong><p>{reason}</p></span></div>)}<div className="decision-row conditional"><AlertCircle/><span><strong>Check this next</strong><p>{item.condition}</p></span></div></div></section><section className="detail-panel detail-panel--actions"><span className="product-eyebrow">Your next moves</span><h2>Three small steps</h2><div className="next-step-list"><span><b>01</b><p><strong>Check the academic rule</strong><small>Use your transcript and module descriptions.</small></p><Link href="/profile">Start <ArrowRight/></Link></span><span><b>02</b><p><strong>Confirm the deadline</strong><small>Check the current official cycle.</small></p><a href={item.sourceUrl} target="_blank" rel="noreferrer">Verify <ArrowRight/></a></span><span><b>03</b><p><strong>Plan the money</strong><small>Keep conditional awards separate.</small></p><Link href="/workspace/funding">Plan <ArrowRight/></Link></span></div></section></main><aside className="decision-summary"><span className="product-eyebrow">Your snapshot</span><h2>{item.matchScore?`${item.matchScore}% match`:item.match}</h2><p>{item.matchScore?"This route matches several known parts of your profile.":"Complete your profile and we will calculate your alignment."}</p><dl><div><dt>Academic</dt><dd>Aligned</dd></div><div><dt>Evidence</dt><dd>Needs work</dd></div><div><dt>Funding</dt><dd>{item.kind==="Scholarship"?"Award dependent":"Review needed"}</dd></div><div><dt>Source</dt><dd>{item.freshness}</dd></div></dl><small><ShieldCheck/> Planning score—not acceptance odds.</small></aside></div>}
function EligibilityPanel({item}:{item:Opportunity}){const reqs=[["Citizenship and residence","Pass","Profile confirms Pakistan"],["Academic qualification","Pass","Relevant bachelor’s degree declared"],["Subject prerequisites","Review",item.condition],["English language","Missing","Accepted score is not yet documented"],["Application timing","Pass",`Target intake precedes ${item.deadline}`]];return <section className="detail-panel wide"><span className="product-eyebrow">Atomic eligibility checks</span><h2>Every rule stays inspectable.</h2><div className="eligibility-table">{reqs.map(([name,state,note])=><div key={name}><span>{state==="Pass"?<CheckCircle2/>:<AlertCircle/>}<strong>{name}</strong></span><Status text={state}/><p>{note}</p><button onClick={() => window.location.href = "/help"}>View rule <ArrowRight/></button></div>)}</div></section>}
function FundingPanel({item}:{item:Opportunity}){return <div className="funding-detail"><section className="detail-panel"><span className="product-eyebrow">Published value</span><h2>{item.value}</h2><p>Displayed exactly as a planning signal. Award value is not deducted from costs until confirmed.</p><div className="cost-stack"><span><b>Estimated first-year cost</b><strong>PKR 9.2m</strong></span><span><b>Documented contribution</b><strong>PKR 3.4m</strong></span><span className="gap"><b>Unresolved gap</b><strong>PKR 5.8m</strong></span></div></section><section className="detail-panel"><span className="product-eyebrow">Funding conditions</span><h2>Keep conditional money separate.</h2><ul className="check-list"><li><Check/> Tuition or award value needs current-cycle verification</li><li><Check/> Living-cost assumption remains editable</li><li><AlertCircle/> No scholarship is counted as confirmed funding</li></ul><Link href="/workspace/funding">Build detailed scenario <ArrowRight/></Link></section></div>}
function TimelinePanel({item}:{item:Opportunity}){return <section className="detail-panel wide"><span className="product-eyebrow">Deadline plan</span><h2>Work backward from {item.deadline}.</h2><div className="route-timeline">{[["Now","Confirm requirements and evidence"],["Next 14 days","Request documents and referee"],["Before submission","Finalize writing and funding proof"],[item.deadline,"Submit on official portal"]].map(([date,title],i)=><div key={date}><b>{i+1}</b><span><small>{date}</small><strong>{title}</strong></span>{i<3?<Clock3/>:<Check/>}</div>)}</div></section>}
function SourcesPanel({item}:{item:Opportunity}){ const officialUrl = item.sourceUrl; const reviewed = item.lastVerifiedAt ? new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(item.lastVerifiedAt)) : "verification pending"; const open=()=>officialUrl&&window.open(officialUrl,"_blank","noopener,noreferrer"); return <section className="detail-panel wide"><span className="product-eyebrow">Source transparency</span><h2>Facts are versioned, not silently overwritten.</h2><div className="source-list"><article><Database/><span><strong>Official {item.kind.toLowerCase()} page</strong><small>Primary source · reviewed {reviewed}</small></span><Status text={item.freshness}/><button disabled={!officialUrl} onClick={open}>{officialUrl?"Open source":"Source pending"} <ArrowRight/></button></article><article><FileText/><span><strong>Current catalogue record</strong><small>Primary-source facts · requirement comparison</small></span><Status text={item.freshness}/><button disabled={!officialUrl} onClick={open}>View official record <Eye/></button></article><article><CalendarDays/><span><strong>Application cycle timeline</strong><small>{item.deadlineNote}</small></span><Status text={item.deadlineAt?"Verified":"Missing"}/><button disabled={!officialUrl} onClick={open}>Verify deadline <ArrowRight/></button></article></div></section>}

export function SettingsCenter({ section = "account", access = { plan: "free", active: false } }: { section?: "account" | "notifications" | "privacy" | "plan"; access?: ProductAccess }) { const [active,setActive]=useState(section); const [saved,setSaved]=useState(false); const save=()=>{setSaved(true);window.setTimeout(()=>setSaved(false),2200)}; return <div className="complete-screen settings-screen"><header className="complete-head"><div><span className="product-eyebrow">Workspace settings</span><h1>Account and preferences.</h1><p>Control notifications, privacy, security and plan details without changing academic evidence.</p></div>{saved&&<span className="save-state" role="status"><Check/> Changes saved</span>}</header><div className="settings-layout"><nav>{[["account",UserRound,"Account"],["notifications",Bell,"Notifications"],["privacy",ShieldCheck,"Privacy & data"],["plan",WalletCards,"Plan & billing"]].map(([id,Icon,label])=><button className={active===id?"active":""} key={String(id)} onClick={()=>setActive(id as typeof active)}><Icon size={17}/>{String(label)}<ArrowRight/></button>)}</nav><main>{active==="account"&&<AccountSettings onSave={save}/>} {active==="notifications"&&<NotificationSettings onSave={save}/>} {active==="privacy"&&<PrivacySettings onSave={save}/>} {active==="plan"&&<PlanSettings access={access}/>}</main></div></div>}
function SettingsSection({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <section className="settings-section"><header><h2>{title}</h2><p>{text}</p></header><div>{children}</div></section>}
function AccountSettings({onSave}:{onSave:()=>void}){return <><SettingsSection title="Personal account" text="Used for account communication, not eligibility decisions."><div className="settings-form"><label>Display name<input defaultValue="Haidar Ali"/></label><label>Email address<input type="email" defaultValue="haidar@example.com"/></label><label>Timezone<span className="complete-select"><select defaultValue="Asia/Karachi"><option>Asia/Karachi</option><option>Asia/Kolkata</option><option>Asia/Dhaka</option></select><ChevronDown/></span></label><label>Interface language<span className="complete-select"><select defaultValue="English"><option>English</option><option>Urdu</option><option>Hindi</option><option>Bangla</option></select><ChevronDown/></span></label></div><button className="settings-save" onClick={onSave}><Save/> Save account</button></SettingsSection><SettingsSection title="Security" text="Protect access to private student documents."><SettingsRow icon={KeyRound} title="Password" text="Last changed 24 July 2026" action="Change password"/><SettingsRow icon={ShieldCheck} title="Two-step verification" text="Recommended before uploading financial evidence" action="Set up"/><SettingsRow icon={Clock3} title="Active sessions" text="1 current Windows session in Pakistan" action="Review"/></SettingsSection></>}
function NotificationSettings({onSave}:{onSave:()=>void}){return <SettingsSection title="Notification channels" text="Critical deadline and security events remain visible in-app."><div className="preference-list"><Preference title="Deadline reminders" text="7 days, 3 days, 1 day and overdue" email/><Preference title="Requirement changes" text="When a verified rule changes an active application" email/><Preference title="Referee activity" text="Invitation opened, submitted or expired" email/><Preference title="Source freshness" text="Weekly summary for saved opportunities"/><Preference title="Product guidance" text="Occasional workflow tips" defaultOn={false}/></div><button className="settings-save" onClick={onSave}><Save/> Save preferences</button></SettingsSection>}
function PrivacySettings({onSave}:{onSave:()=>void}){return <><SettingsSection title="Privacy controls" text="CandidRoute keeps student documents private by default."><SettingsRow icon={Lock} title="Document access" text="Only your account can open signed document links" action="Review access"/><SettingsRow icon={Download} title="Export your data" text="Profile, tasks, applications and audit history" action="Request export"/><SettingsRow icon={Eye} title="Activity history" text="See important account and data-access events" action="View history"/></SettingsSection><section className="danger-zone"><div><Trash2/><span><strong>Delete CandidRoute account</strong><small>Starts a recoverable 14-day deletion period.</small></span></div><button onClick={onSave}>Request deletion</button></section><button className="settings-save" onClick={onSave}><Save/> Save privacy settings</button></>}
function PlanSettings({access}:{access:ProductAccess}){const pro=access.plan==="pro"&&access.active;return <><section className="plan-card"><div><span className="product-eyebrow">Current plan</span><h2>{pro?"CandidRoute Pro":"Free access"}</h2><p>{pro?"Your complete planning and application workspace is unlocked.":"Your free pathway report and previews remain available."}</p></div><strong>{pro?"Pro":"Free"}<small>{pro?"active":"current plan"}</small></strong></section><SettingsSection title="Included" text={pro?"All Pro modules are available on this account.":"Upgrade to unlock the complete workspace."}><ul className="plan-features"><li><Check/> Complete profile and pathway report</li><li><Check/> Explainable programme and scholarship recommendations</li><li><Check/> Application, task and evidence workspace</li><li><Check/> Deadline and source-change notifications</li></ul></SettingsSection></>}
function SettingsRow({icon:Icon,title,text,action}:{icon:typeof Settings;title:string;text:string;action:string}){const [prepared,setPrepared]=useState(false);return <div className="settings-row"><span><Icon/></span><div><strong>{title}</strong><small>{text}</small></div><button onClick={()=>{setPrepared(true);window.setTimeout(()=>setPrepared(false),1800)}}>{prepared?"Prepared":action}{prepared?<Check/>:<ArrowRight/>}</button></div>}
function Preference({title,text,email=false,defaultOn=true}:{title:string;text:string;email?:boolean;defaultOn?:boolean}){const [on,setOn]=useState(defaultOn);return <div className="preference"><div><strong>{title}</strong><small>{text}</small>{email&&<em><Mail/> Email and in-app</em>}</div><button className={on?"on":""} onClick={()=>setOn(!on)} aria-pressed={on}><i/></button></div>}
function Status({text}:{text:string}){const lower=text.toLowerCase();const tone=lower.includes("verified")||lower.includes("pass")||lower.includes("complete")?"green":lower.includes("missing")||lower.includes("action")?"red":lower.includes("review")||lower.includes("condition")||lower.includes("provisional")?"amber":"blue";return <span className={`status-pill status-pill--${tone}`}>{text}</span>}
function ToastMessage({title,text}:{title:string;text:string}){return <div className="complete-toast" role="status" aria-live="polite"><CheckCircle2/><span><strong>{title}</strong><small>{text}</small></span></div>}
