-- Curated beta dataset. Values are evidence-linked and intentionally narrow.
-- Immigration and cost facts require scheduled review; rankings are contextual only.

insert into public.source_records(canonical_url,source_type,owner_name,country_code,status,last_verified_at,next_review_at,verification_notes)
values
('https://www.gov.uk/student-visa','government','UK Home Office','GB','verified','2026-08-04','2026-09-04','Student route overview and fee'),
('https://www.gov.uk/student-visa/money','government','UK Home Office','GB','verified','2026-08-04','2026-09-04','Student financial requirement'),
('https://www.gov.uk/guidance/immigration-rules/immigration-rules-appendix-student','government','UK Home Office','GB','verified','2026-08-04','2026-09-04','Student work conditions'),
('https://www.leeds.ac.uk/international-fees-costs/doc/living-expenses','institution','University of Leeds','GB','verified','2026-08-04','2026-11-04','Leeds student budget ranges'),
('https://www.make-it-in-germany.com/en/visa-residence/types/studying','government','Federal Government of Germany','DE','verified','2026-08-04','2026-09-04','Study visa, funding and work rules'),
('https://www.daad.de/en/studying-in-germany/living-in-germany/finances/','government_agency','DAAD','DE','verified','2026-08-04','2026-11-04','National student living costs'),
('https://www.daad.de/en/studying-in-germany/living-in-germany/health-insurance/','government_agency','DAAD','DE','verified','2026-08-04','2026-11-04','Student health insurance'),
('https://www.international.tum.de/en/global/exchangestudents/general-information-for-international-students/preparing-your-stay/','institution','Technical University of Munich','DE','verified','2026-08-04','2026-11-04','Munich living-cost range'),
('https://ind.nl/en/required-amounts-income-requirements','government','Dutch Immigration and Naturalisation Service','NL','verified','2026-08-04','2026-09-04','2026 study norm'),
('https://ind.nl/en/about-us/background-articles/international-students-and-the-ind','government','Dutch Immigration and Naturalisation Service','NL','verified','2026-08-04','2026-09-04','Study work and orientation-year rules'),
('https://www.studyinnl.org/finances/daily-student-expenses-and-cost-of-living-in-the-netherlands','government_agency','Nuffic / Study in NL','NL','verified','2026-08-04','2026-11-04','National student cost and housing range'),
('https://www.studyinnl.org/plan-your-stay/healthcare-insurance','government_agency','Nuffic / Study in NL','NL','verified','2026-08-04','2026-11-04','International student health insurance'),
('https://www.irishimmigration.ie/coming-to-study-in-ireland/what-are-my-study-options/a-fee-paying-private-primary-or-secondary-school/information-on-student-finances/','government','Immigration Service Delivery Ireland','IE','verified','2026-08-04','2026-09-04','Student financial requirement'),
('https://www.irishimmigration.ie/coming-to-study-in-ireland/frequently-asked-questions-for-students/','government','Immigration Service Delivery Ireland','IE','verified','2026-08-04','2026-09-04','Student work and graduate permission'),
('https://www.educationinireland.com/en/living-in-ireland/health-insurance','government_agency','Education in Ireland','IE','verified','2026-08-04','2026-11-04','Non-EEA health insurance'),
('https://www.educationinireland.com/en/plan-your-study-abroad/student-accommodation','government_agency','Education in Ireland','IE','verified','2026-08-04','2026-11-04','Accommodation and deposit guidance'),
('https://www.tcd.ie/study/international/welcome/cost-of-living/','institution','Trinity College Dublin','IE','verified','2026-08-04','2026-11-04','Dublin annual student budget'),
('https://www.leeds.ac.uk/admissions-qualifications/21832/pakistan','institution','University of Leeds','GB','verified','2026-08-04','2026-11-04','Pakistan qualification equivalence'),
('https://www.leeds.ac.uk/dir-record/profiles/21864/india','institution','University of Leeds','GB','verified','2026-08-04','2026-11-04','India qualification equivalence'),
('https://www.leeds.ac.uk/admissions-qualifications/21774/bangladesh','institution','University of Leeds','GB','verified','2026-08-04','2026-11-04','Bangladesh qualification equivalence'),
('https://www.tcd.ie/study/country/pakistan/','institution','Trinity College Dublin','IE','verified','2026-08-04','2026-11-04','South Asia postgraduate entry context'),
('https://www.topuniversities.com/universities/university-leeds','ranking_publisher','QS','GB','verified','2026-08-04','2027-07-01','QS WUR history'),
('https://www.topuniversities.com/universities/technical-university-munich','ranking_publisher','QS','DE','verified','2026-08-04','2027-07-01','QS WUR history'),
('https://www.topuniversities.com/universities/delft-university-technology','ranking_publisher','QS','NL','verified','2026-08-04','2027-07-01','QS WUR history'),
('https://www.topuniversities.com/universities/trinity-college-dublin-university-dublin','ranking_publisher','QS','IE','verified','2026-08-04','2027-07-01','QS WUR history')
on conflict(canonical_url) do update set status=excluded.status,last_verified_at=excluded.last_verified_at,next_review_at=excluded.next_review_at,verification_notes=excluded.verification_notes;

insert into public.countries(code,slug,name,flag_emoji,currency_code,currency_symbol,primary_language,student_route_name,visa_difficulty,visa_fee_amount,visa_fee_currency,proof_funds_amount,proof_funds_currency,proof_funds_period_months,work_hours_term,post_study_months,monthly_cost_low,monthly_cost_high,cost_currency,summary,healthcare_summary,work_summary,post_study_summary,climate_summary,community_summary,visa_uncertainty,state,last_verified_at,next_review_at)
values
('GB','united-kingdom','United Kingdom','🇬🇧','GBP','£','English','Student visa','moderate',558,'GBP',10539,'GBP',9,20,18,1171,2200,'GBP','Large programme market with clear sponsor and visa rules; cost varies sharply by city.','Student applicants normally pay the Immigration Health Surcharge and receive NHS access under its terms.','Degree-level students at eligible sponsors are normally limited to 20 hours per week during term.','The Graduate route is scheduled at 18 months for non-doctoral applications made from 1 January 2027; verify before planning.','Temperate and often wet, with mild summers and cool winters.','Major university cities have established Muslim and South Asian communities; proximity to facilities must be checked by postcode.','Rules and fees change frequently; CAS timing, financial evidence and course-specific ATAS needs can alter readiness.','published','2026-08-04','2026-09-04'),
('DE','germany','Germany','🇩🇪','EUR','€','German','National study visa / residence permit','moderate',75,'EUR',11904,'EUR',12,20,18,900,1200,'EUR','Strong public-university value with more programme and city variation than tuition headlines imply.','Compliant health insurance is mandatory for enrolment and residence purposes.','Students may generally work up to 140 full or 280 half days yearly, or up to 20 hours weekly under the current route.','Graduates can generally seek qualified employment for up to 18 months after study.','Four seasons; colder winters and regional variation between maritime and continental areas.','Large cities and university towns commonly provide mosques, halal options and international student societies; local availability varies.','Blocked-account levels and recognition steps change; programme language and degree equivalence remain institution-specific.','published','2026-08-04','2026-09-04'),
('NL','netherlands','Netherlands','🇳🇱','EUR','€','Dutch','Residence permit for study','moderate',254,'EUR',13569.24,'EUR',12,16,12,1000,1500,'EUR','English-taught options are strong, but housing scarcity materially affects feasibility.','Study-only students generally need adequate private or home-country cover; Dutch public insurance rules change when paid work begins.','Non-EU students can normally work up to 16 hours weekly or only in summer, with employer permit conditions.','Eligible graduates may apply for a one-year orientation permit.','Maritime climate with mild summers, cool winters, wind and frequent rain.','Amsterdam, Rotterdam, The Hague and major student cities have visible Muslim and South Asian communities; check commute and local facilities.','Recognised-sponsor status, annual study norm and housing availability are major dependencies.','published','2026-08-04','2026-09-04'),
('IE','ireland','Ireland','🇮🇪','EUR','€','English','Long Stay D study visa / Stamp 2','moderate',60,'EUR',10000,'EUR',12,20,24,1200,2250,'EUR','English-speaking study route with a smaller institution market and severe accommodation pressure in Dublin.','Private medical insurance is compulsory for non-EU/EEA students.','Stamp 2 students may normally work 20 hours weekly in term and 40 hours during specified vacations.','Level 9 or above graduates may receive up to 24 months under the Third Level Graduate Programme; Level 8 is normally 12 months.','Mild maritime climate with frequent rain, wind and limited temperature extremes.','Dublin and other university cities have active Muslim and South Asian communities; housing location determines practical access.','Visa finance, eligible-programme status, registration and accommodation availability must all be verified.','published','2026-08-04','2026-09-04')
on conflict(code) do update set summary=excluded.summary,state=excluded.state,last_verified_at=excluded.last_verified_at,next_review_at=excluded.next_review_at;

insert into public.cities(country_code,slug,name,monthly_cost_low,monthly_cost_high,accommodation_low,accommodation_high,deposit_summary,transport_summary,safety_summary,climate_summary,community_summary,source_id,confidence,state,last_verified_at,next_review_at)
values
('GB','leeds','Leeds',862,1833,507,1300,'Private and university contract terms vary; confirm the exact refundable deposit before payment.','Walkable student areas with bus and rail links; budget separately for inter-city travel.','Use standard city precautions and institution safety services; no personal safety guarantee is implied.','Cool, wet winters and mild summers.','Established Muslim and South Asian communities with multiple halal and worship options; check distance from the chosen campus.',(select id from public.source_records where canonical_url='https://www.leeds.ac.uk/international-fees-costs/doc/living-expenses'),85,'published','2026-08-04','2026-11-04'),
('GB','london','London',1529,2600,900,1800,'Deposits and advance-rent requirements can materially increase arrival cash needs.','Extensive public transport but materially higher monthly travel costs.','Safety varies by neighbourhood and travel time; compare campus-to-home routes.','Mild but wet climate; urban heat can raise summer temperatures.','Large and diverse Muslim and South Asian communities across multiple boroughs.',(select id from public.source_records where canonical_url='https://www.gov.uk/student-visa/money'),60,'published','2026-08-04','2026-10-04'),
('GB','manchester','Manchester',1050,1900,550,1200,'Confirm whether utilities and council-tax exemptions are reflected in the contract.','Strong tram, bus and rail network; student-area commute varies.','Use university and local guidance when selecting neighbourhoods.','Cool, wet and often cloudy with mild summers.','Large Muslim and South Asian communities and broad halal availability.',(select id from public.source_records where canonical_url='https://www.gov.uk/student-visa/money'),55,'published','2026-08-04','2026-10-04'),
('DE','munich','Munich',1200,1700,300,1000,'Student-residence deposits can be lower than private-market deposits; TUM cites about €500 in one student programme.','Dense public transport; student tickets and the Deutschlandticket can reduce cost.','Generally well-served urban environment; use local guidance for neighbourhood-level decisions.','Cold winters and warm summers; Alpine weather changes can be rapid.','Established international and Muslim communities; halal access is broad but campus proximity varies.',(select id from public.source_records where canonical_url='https://www.international.tum.de/en/global/exchangestudents/general-information-for-international-students/preparing-your-stay/'),82,'published','2026-08-04','2026-11-04'),
('DE','saarbrucken','Saarbrücken',900,1150,300,600,'Confirm deposit and utilities directly with the housing provider.','Compact city with buses and regional rail; semester arrangements may cover some transport.','Use university and municipal guidance for current local conditions.','Cool winters, mild summers and year-round rainfall.','Smaller community than major German metros; verify halal and worship access relative to campus.',(select id from public.source_records where canonical_url='https://www.daad.de/en/studying-in-germany/living-in-germany/finances/'),60,'published','2026-08-04','2026-11-04'),
('NL','delft','Delft',1050,1550,450,1000,'Housing providers may require deposits and advance payments; never rely on an unverified listing.','Cycling is central; local bus and national rail connections are strong.','Cycle safety and housing scams are practical student risks; use institution-approved channels.','Mild, windy and wet maritime climate.','International student community with access to nearby Rotterdam and The Hague facilities.',(select id from public.source_records where canonical_url='https://www.studyinnl.org/finances/daily-student-expenses-and-cost-of-living-in-the-netherlands'),68,'published','2026-08-04','2026-11-04'),
('NL','amsterdam','Amsterdam',1300,1900,650,1250,'High demand increases scam and advance-payment risk; institution-supported housing should be prioritised.','Cycling and public transport are extensive but add recurring cost.','Housing fraud and cycle safety deserve explicit checks alongside normal city precautions.','Mild, windy and frequently wet.','Large diverse Muslim and South Asian communities with broad food and worship access.',(select id from public.source_records where canonical_url='https://www.studyinnl.org/finances/daily-student-expenses-and-cost-of-living-in-the-netherlands'),65,'published','2026-08-04','2026-11-04'),
('IE','dublin','Dublin',1754,2254,750,1333,'A deposit equivalent to one month’s rent is commonly required, with rent paid in advance.','Bus, rail and tram options are available; accommodation location drives commute cost.','Accommodation scams and late-night travel planning are material student considerations.','Mild, windy and rainy with limited temperature extremes.','Large international, Muslim and South Asian communities with broad halal and worship access.',(select id from public.source_records where canonical_url='https://www.tcd.ie/study/international/welcome/cost-of-living/'),88,'published','2026-08-04','2026-11-04'),
('IE','cork','Cork',1200,1800,650,1100,'A one-month refundable deposit is common; verify inventory and lease terms.','Bus-based local transport with a compact centre; housing distance affects commute.','Use institution accommodation services and standard urban precautions.','Mild and rainy maritime climate.','Active international community; Muslim and South Asian facilities exist but are less distributed than Dublin.',(select id from public.source_records where canonical_url='https://www.educationinireland.com/en/plan-your-study-abroad/student-accommodation'),58,'published','2026-08-04','2026-11-04')
on conflict(country_code,slug) do update set monthly_cost_low=excluded.monthly_cost_low,monthly_cost_high=excluded.monthly_cost_high,state=excluded.state,last_verified_at=excluded.last_verified_at,next_review_at=excluded.next_review_at;

insert into public.country_facts(country_code,category,fact_key,label,value,qualification,source_id,confidence,effective_from,state,last_verified_at,next_review_at)
values
('GB','proof_funds','maintenance_london','Visa maintenance — London','{"amount":1529,"currency":"GBP","period":"month","maximum_months":9}','Funds normally held for 28 consecutive days; tuition balance is additional.',(select id from public.source_records where canonical_url='https://www.gov.uk/student-visa/money'),98,'2026-07-01','published','2026-08-04','2026-09-04'),
('GB','proof_funds','maintenance_outside_london','Visa maintenance — outside London','{"amount":1171,"currency":"GBP","period":"month","maximum_months":9}','This is a visa threshold, not a personal spending forecast.',(select id from public.source_records where canonical_url='https://www.gov.uk/student-visa/money'),98,'2026-07-01','published','2026-08-04','2026-09-04'),
('GB','work','term_work','Term-time work','{"hours_per_week":20}','Applies to eligible full-time degree-level study at a compliant sponsor.',(select id from public.source_records where canonical_url='https://www.gov.uk/guidance/immigration-rules/immigration-rules-appendix-student'),97,'2026-07-01','published','2026-08-04','2026-09-04'),
('GB','post_study','graduate_route','Graduate route','{"months":18,"doctoral_months":36}','18 months applies to non-doctoral applications from 1 January 2027 under current published rules.',(select id from public.source_records where canonical_url='https://www.gov.uk/student-visa'),95,'2027-01-01','published','2026-08-04','2026-09-04'),
('DE','proof_funds','blocked_account_2026','2026 funding proof','{"amount":11904,"currency":"EUR","period":"year","monthly_release":992}','Scholarship or recognised declaration may be alternatives.',(select id from public.source_records where canonical_url='https://www.make-it-in-germany.com/en/visa-residence/types/studying'),96,'2026-01-01','published','2026-08-04','2026-09-04'),
('DE','work','study_work','Student work allowance','{"full_days":140,"half_days":280,"weekly_hours_alternative":20}','Student assistant roles can be treated differently; confirm individual permit conditions.',(select id from public.source_records where canonical_url='https://www.make-it-in-germany.com/en/visa-residence/types/studying'),94,'2026-01-01','published','2026-08-04','2026-09-04'),
('DE','cost','national_monthly','Indicative monthly living cost','{"low":900,"high":1200,"currency":"EUR"}','City and accommodation choice dominate the range.',(select id from public.source_records where canonical_url='https://www.daad.de/en/studying-in-germany/living-in-germany/finances/'),85,'2026-01-01','published','2026-08-04','2026-11-04'),
('DE','healthcare','insurance','Health insurance','{"required":true}','Equivalent compliant coverage is required for enrolment or visa stages.',(select id from public.source_records where canonical_url='https://www.daad.de/en/studying-in-germany/living-in-germany/health-insurance/'),95,'2026-01-01','published','2026-08-04','2026-11-04'),
('NL','proof_funds','study_norm_2026','2026 university study norm','{"amount":1130.77,"currency":"EUR","period":"month","months":12}','Does not include tuition.',(select id from public.source_records where canonical_url='https://ind.nl/en/required-amounts-income-requirements'),98,'2026-01-01','published','2026-08-04','2026-09-04'),
('NL','work','term_work','Student work allowance','{"hours_per_week":16,"summer_alternative":true}','Employer work-permit conditions apply.',(select id from public.source_records where canonical_url='https://ind.nl/en/about-us/background-articles/international-students-and-the-ind'),95,'2026-01-01','published','2026-08-04','2026-09-04'),
('NL','post_study','orientation_year','Orientation year','{"months":12}','Eligibility and application timing must be checked with IND.',(select id from public.source_records where canonical_url='https://ind.nl/en/about-us/background-articles/international-students-and-the-ind'),95,'2026-01-01','published','2026-08-04','2026-09-04'),
('NL','housing','national_room_range','Indicative room cost','{"low":450,"high":1000,"currency":"EUR","period":"month"}','Amsterdam is usually above smaller student cities.',(select id from public.source_records where canonical_url='https://www.studyinnl.org/finances/daily-student-expenses-and-cost-of-living-in-the-netherlands'),88,'2026-01-01','published','2026-08-04','2026-11-04'),
('IE','proof_funds','annual_finance','Student finance requirement','{"amount":10000,"currency":"EUR","period":"year"}','Tuition is additional; shorter courses use published monthly rules.',(select id from public.source_records where canonical_url='https://www.irishimmigration.ie/coming-to-study-in-ireland/what-are-my-study-options/a-fee-paying-private-primary-or-secondary-school/information-on-student-finances/'),98,'2025-06-30','published','2026-08-04','2026-09-04'),
('IE','work','stamp_2_work','Stamp 2 work allowance','{"term_hours_per_week":20,"vacation_hours_per_week":40}','Vacation periods are specifically defined by immigration rules.',(select id from public.source_records where canonical_url='https://www.irishimmigration.ie/coming-to-study-in-ireland/frequently-asked-questions-for-students/'),96,'2026-01-01','published','2026-08-04','2026-09-04'),
('IE','post_study','third_level_graduate','Third Level Graduate Programme','{"level_8_months":12,"level_9_plus_months":24}','Level 9+ permission is normally issued in two 12-month blocks.',(select id from public.source_records where canonical_url='https://www.irishimmigration.ie/coming-to-study-in-ireland/frequently-asked-questions-for-students/'),96,'2026-01-01','published','2026-08-04','2026-09-04'),
('IE','healthcare','private_insurance','Private medical insurance','{"required":true}','Required for non-EU/EEA students and must meet immigration conditions.',(select id from public.source_records where canonical_url='https://www.educationinireland.com/en/living-in-ireland/health-insurance'),95,'2026-01-01','published','2026-08-04','2026-11-04')
on conflict(country_code,fact_key) do update set value=excluded.value,qualification=excluded.qualification,state=excluded.state,last_verified_at=excluded.last_verified_at,next_review_at=excluded.next_review_at;

insert into public.institutions(slug,official_name,short_name,institution_type,country_code,city_id,website_url,admissions_url,public_private,degree_awarding,international_sponsor_status,summary,state,last_verified_at,next_review_at)
values
('university-of-leeds','University of Leeds','Leeds','university','GB',(select id from public.cities where country_code='GB' and slug='leeds'),'https://www.leeds.ac.uk','https://www.leeds.ac.uk/masters','public',true,'UK student sponsor; verify register status before CAS','Research-intensive university with broad taught postgraduate provision.','published','2026-08-04','2026-11-04'),
('university-of-manchester','University of Manchester','Manchester','university','GB',(select id from public.cities where country_code='GB' and slug='manchester'),'https://www.manchester.ac.uk','https://www.manchester.ac.uk/study/masters/','public',true,'Verify current UK sponsor register','Large research university with broad STEM, business and humanities provision.','published','2026-08-04','2026-11-04'),
('university-of-sheffield','University of Sheffield','Sheffield','university','GB',null,'https://www.sheffield.ac.uk','https://www.sheffield.ac.uk/postgraduate','public',true,'Verify current UK sponsor register','Research university with engineering, computing and interdisciplinary options.','published','2026-08-04','2026-11-04'),
('technical-university-of-munich','Technical University of Munich','TUM','university','DE',(select id from public.cities where country_code='DE' and slug='munich'),'https://www.tum.de','https://www.tum.de/en/studies/application','public',true,'German state-recognised institution; verify programme route','Research university focused on engineering, computing, science and management.','published','2026-08-04','2026-11-04'),
('saarland-university','Saarland University','Saarland','university','DE',(select id from public.cities where country_code='DE' and slug='saarbrucken'),'https://www.uni-saarland.de','https://www.uni-saarland.de/en/study/application.html','public',true,'German state-recognised institution; verify programme route','Research university with a particularly strong computer-science ecosystem.','published','2026-08-04','2026-11-04'),
('rwth-aachen','RWTH Aachen University','RWTH Aachen','university','DE',null,'https://www.rwth-aachen.de','https://www.rwth-aachen.de/go/id/bqrn/lidx/1','public',true,'German state-recognised institution; verify programme route','Large technical university with extensive engineering and science provision.','published','2026-08-04','2026-11-04'),
('tu-delft','Delft University of Technology','TU Delft','university','NL',(select id from public.cities where country_code='NL' and slug='delft'),'https://www.tudelft.nl','https://www.tudelft.nl/en/education/admission-and-application','public',true,'Verify IND recognised-sponsor register','Technology-focused research university with competitive MSc admissions.','published','2026-08-04','2026-11-04'),
('university-of-amsterdam','University of Amsterdam','UvA','university','NL',(select id from public.cities where country_code='NL' and slug='amsterdam'),'https://www.uva.nl','https://www.uva.nl/en/education/admissions/admissions.html','public',true,'Verify IND recognised-sponsor register','Broad research university with many English-taught graduate programmes.','published','2026-08-04','2026-11-04'),
('eindhoven-university-of-technology','Eindhoven University of Technology','TU/e','university','NL',null,'https://www.tue.nl','https://www.tue.nl/en/education/become-a-tue-student','public',true,'Verify IND recognised-sponsor register','Technical university connected to a major engineering and technology region.','published','2026-08-04','2026-11-04'),
('trinity-college-dublin','Trinity College Dublin','Trinity','university','IE',(select id from public.cities where country_code='IE' and slug='dublin'),'https://www.tcd.ie','https://www.tcd.ie/courses/postgraduate/','public',true,'Verify current eligible programme and TrustEd/ILEP position','Research university in central Dublin with broad postgraduate provision.','published','2026-08-04','2026-11-04'),
('university-college-dublin','University College Dublin','UCD','university','IE',(select id from public.cities where country_code='IE' and slug='dublin'),'https://www.ucd.ie','https://www.ucd.ie/global/study-at-ucd/','public',true,'Verify current eligible programme and TrustEd/ILEP position','Large research university with a broad international programme portfolio.','published','2026-08-04','2026-11-04'),
('university-college-cork','University College Cork','UCC','university','IE',(select id from public.cities where country_code='IE' and slug='cork'),'https://www.ucc.ie','https://www.ucc.ie/en/study/postgrad/','public',true,'Verify current eligible programme and TrustEd/ILEP position','Research university offering broad postgraduate study in Cork.','published','2026-08-04','2026-11-04')
on conflict(slug) do update set official_name=excluded.official_name,summary=excluded.summary,state=excluded.state,last_verified_at=excluded.last_verified_at,next_review_at=excluded.next_review_at;

insert into public.campuses(institution_id,name,city_id,is_main,state,last_verified_at,next_review_at)
select i.id,i.official_name || ' main campus',i.city_id,true,'published','2026-08-04','2026-11-04'
from public.institutions i where i.city_id is not null
on conflict(institution_id,name) do update set state=excluded.state,last_verified_at=excluded.last_verified_at,next_review_at=excluded.next_review_at;

insert into public.institution_rankings(institution_id,publisher,ranking_name,edition_year,rank_min,rank_max,rank_label,methodology_url,source_id,state,last_verified_at,next_review_at)
values
((select id from public.institutions where slug='university-of-leeds'),'QS','World University Rankings',2026,86,86,'86','https://www.topuniversities.com/qs-world-university-rankings/methodology',(select id from public.source_records where canonical_url='https://www.topuniversities.com/universities/university-leeds'),'published','2026-08-04','2027-07-01'),
((select id from public.institutions where slug='technical-university-of-munich'),'QS','World University Rankings',2026,22,22,'=22','https://www.topuniversities.com/qs-world-university-rankings/methodology',(select id from public.source_records where canonical_url='https://www.topuniversities.com/universities/technical-university-munich'),'published','2026-08-04','2027-07-01'),
((select id from public.institutions where slug='tu-delft'),'QS','World University Rankings',2026,47,47,'=47','https://www.topuniversities.com/qs-world-university-rankings/methodology',(select id from public.source_records where canonical_url='https://www.topuniversities.com/universities/delft-university-technology'),'published','2026-08-04','2027-07-01'),
((select id from public.institutions where slug='trinity-college-dublin'),'QS','World University Rankings',2026,75,75,'75','https://www.topuniversities.com/qs-world-university-rankings/methodology',(select id from public.source_records where canonical_url='https://www.topuniversities.com/universities/trinity-college-dublin-university-dublin'),'published','2026-08-04','2027-07-01')
on conflict(institution_id,publisher,ranking_name,edition_year,subject) do nothing;

insert into public.qualification_equivalencies(institution_id,origin_country,study_level,qualification_pattern,minimum_result,evaluation_state,notes,source_id,state,last_verified_at,next_review_at)
values
((select id from public.institutions where slug='university-of-leeds'),'Pakistan','postgraduate','Four-year bachelor or two-year master after shorter bachelor','UK 2:1 mapping: typically 70% or GPA 2.8–3.0','published_threshold','Programme-specific requirements may be higher.',(select id from public.source_records where canonical_url='https://www.leeds.ac.uk/admissions-qualifications/21832/pakistan'),'published','2026-08-04','2026-11-04'),
((select id from public.institutions where slug='university-of-leeds'),'India','postgraduate','Three- or four-year bachelor','UK 2:1 mapping: typically 60% / first class','published_threshold','Board, institution and programme conditions can change the assessment.',(select id from public.source_records where canonical_url='https://www.leeds.ac.uk/dir-record/profiles/21864/india'),'published','2026-08-04','2026-11-04'),
((select id from public.institutions where slug='university-of-leeds'),'Bangladesh','postgraduate','Four-year bachelor or one- to two-year master','UK 2:1 mapping: typically 70%, master GPA 3.0 or bachelor GPA 3.2','published_threshold','Programme-specific requirements may be higher.',(select id from public.source_records where canonical_url='https://www.leeds.ac.uk/admissions-qualifications/21774/bangladesh'),'published','2026-08-04','2026-11-04'),
((select id from public.institutions where slug='trinity-college-dublin'),'Pakistan','postgraduate','Recognised bachelor degree','Equivalent of Irish 2.1 honours','case_by_case','Final assessment is made by Academic Registry and the programme may set higher requirements.',(select id from public.source_records where canonical_url='https://www.tcd.ie/study/country/pakistan/'),'published','2026-08-04','2026-11-04'),
((select id from public.institutions where slug='trinity-college-dublin'),'India','postgraduate','Recognised bachelor degree','Equivalent of Irish 2.1 honours','case_by_case','Final assessment is programme-specific.',(select id from public.source_records where canonical_url='https://www.tcd.ie/study/country/pakistan/'),'published','2026-08-04','2026-11-04'),
((select id from public.institutions where slug='trinity-college-dublin'),'Bangladesh','postgraduate','Recognised bachelor degree','Equivalent of Irish 2.1 honours','case_by_case','Final assessment is programme-specific.',(select id from public.source_records where canonical_url='https://www.tcd.ie/study/country/pakistan/'),'published','2026-08-04','2026-11-04')
on conflict(institution_id,origin_country,study_level,qualification_pattern) do update set minimum_result=excluded.minimum_result,evaluation_state=excluded.evaluation_state,notes=excluded.notes,state=excluded.state,last_verified_at=excluded.last_verified_at,next_review_at=excluded.next_review_at;

insert into public.institution_requirements(institution_id,requirement_type,label,description,required,origin_country,study_level,source_id,state,last_verified_at,next_review_at)
values
((select id from public.institutions where slug='university-of-leeds'),'academic','Degree certificate and transcript','Official academic records are needed to establish degree level and programme prerequisites.',true,null,'postgraduate',(select id from public.source_records where canonical_url='https://www.leeds.ac.uk/admissions-qualifications/21832/pakistan'),'published','2026-08-04','2026-11-04'),
((select id from public.institutions where slug='university-of-leeds'),'english','English-language evidence','Typical postgraduate minimum is IELTS 6.5 overall, but programme component scores can be higher.',true,null,'postgraduate',(select id from public.source_records where canonical_url='https://www.leeds.ac.uk/admissions-qualifications/21832/pakistan'),'published','2026-08-04','2026-11-04'),
((select id from public.institutions where slug='trinity-college-dublin'),'academic','Degree certificate and transcript','Evidence must support an Irish 2.1-equivalent result and relevant programme preparation.',true,null,'postgraduate',(select id from public.source_records where canonical_url='https://www.tcd.ie/study/country/pakistan/'),'published','2026-08-04','2026-11-04'),
((select id from public.institutions where slug='trinity-college-dublin'),'english','Recognised English-language result','A high level of English competence is required; use the programme page for exact test thresholds.',true,null,'postgraduate',(select id from public.source_records where canonical_url='https://www.tcd.ie/study/country/pakistan/'),'published','2026-08-04','2026-11-04')
on conflict do nothing;

